name: Code Report

on:
  workflow_run:
    workflows: ['🔥 Firmware Build']
    types:
      - completed

jobs:
  download-artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: '↓ Download code size report'
      uses: actions/download-artifact@v4
      with:
        name: "code-size-report"
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ github.token }}

    - name: '📝 Check Report'
      run: |
        ls -1 -R ${GITHUB_WORKSPACE}
        CODE_SIZE_REPORT=code-size-report.md
        cat ${GITHUB_WORKSPACE}/${CODE_SIZE_REPORT}

        PR_NUMBER=$(jq -r '.workflow_run.pull_requests[0].number' < "$GITHUB_EVENT_PATH")
        echo "Pull Request Number: $PR_NUMBER"

        if [ -s ${GITHUB_WORKSPACE}/${CODE_SIZE_REPORT} ]; then
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "code_size_report=${CODE_SIZE_REPORT}" >> $GITHUB_OUTPUT
        fi

    - name: '📝 Post report'
      if: steps.generate_report.outputs.code_size_report != ''
      uses: thollander/actions-comment-pull-request@v2
      with:
        pr_number: ${{ steps.generate_report.outputs.pr_number }}
        filePath: ${{ github.workspace }}/${{ steps.generate_report.outputs.code_size_report }}
