name: '🔥 Firmware Build'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-size-report:
    runs-on: ubuntu-22.04
    steps:
    - name: '📝 Generate report'
      id: generate_report
      run: |
        CODE_SIZE_REPORT=code-size-report.md
        echo "Test" > ${GITHUB_WORKSPACE}/${CODE_SIZE_REPORT}
        if [ -s ${GITHUB_WORKSPACE}/${CODE_SIZE_REPORT} ]; then
          echo "code_size_report=${CODE_SIZE_REPORT}" >> $GITHUB_OUTPUT
        fi

    - name: '⬆ Upload code report'
      if: steps.generate_report.outputs.code_size_report != ''
      uses: actions/upload-artifact@v4
      with:
        overwrite: true
        name: ${{ steps.generate_report.outputs.code_size_report }}
        path: ${{ github.workspace }}/${{ steps.generate_report.outputs.code_size_report }}
        if-no-files-found: error
